### ISSUE TITLE
checkyesno is not correct in the rc scrip

### ISSUE THREAD

**Issue by 0mp** [aborche/qemu-guest-agent#1]
I don't think this line is correct: https://github.com/aborche/qemu-guest-agent/blob/c967f1792d0ed566ba2e1ebfb5fe3a7a0edf4780/files/qemu-guest-agent.in#L25

This approach prevents users from starting the service without enabling it in /etc/rc.conf with `service servicename onestart`.

**Comment by aborche** [comment]
fixed in d6747940c20b45a0ddd5e8ea9d08fe5a938501e8
