### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by NuxRo** [aborche/qemu-guest-agent#10]
Just installed this on FreeBSD 11 and it works fine (I need it to retrieve the network info from the VM).
Thanks

PS: Tried to also install it on pfSense, but their kernel is missing a lot of the virtio stuff needed to make this work, alas.

**Comment by aborche** [comment]
Try to load virtio modules on pfSense if they exist.
What you see in dmesg?

**Comment by NuxRo** [comment]
Aborche, 

I copied over the virtio_console.ko from FreeBSD to PFSense, loaded it and your qemu-ga started working.
I've opened an issue with them to build virtio_console in future releases.
https://redmine.pfsense.org/issues/9985

Thanks again!

**Comment by JasonSwindle** [comment]
PFSense 2.4.5p1 is out with virtio_console.ko support. :)
