### ISSUE TITLE
Updates? Install? Downloadable Binary package?

### ISSUE THREAD

**Issue by MBfromOK** [aborche/qemu-guest-agent#13]
Any progress on getting the project listed as a FreeBSD port??
If not, has any effort been made to produce an installable binary package (or how would I install this package)?

For what it's worth: I see this note in the Google search I did for qemu-guest-agent:
Site: pfsense Forums - [Feature #9877: QEMU Guest Agent](https://redmine.pfsense.org/issues/9877)

> It looks like that port has not been added to FreeBSD yet. The linked PR shows they added some code to the main qemu port to not break that port when building qemu-guest-agent, but ***there is no emulators/qemu-guest-agent*** in the FreeBSD ports tree.

I am pretty new to system administration, so my apologies if this message has no bearing.
**Edit:** clarity

**Comment by aborche** [comment]
https://github.com/aborche/qemu-guest-agent/releases/tag/v0.1
