### ISSUE TITLE
Support for HardenedBSD - 12.2--HBSD

### ISSUE THREAD

**Issue by ionutnechita** [aborche/qemu-guest-agent#14]
Hi,

I tried to install, but I can't.
From what I notice it is for version QEMU 4.1.1.
But this version is older.

In the port system, I now find QEMU 5.0.1.
Could you help me with this issue?

[logs.txt](https://github.com/aborche/qemu-guest-agent/files/5622923/logs.txt)

**Comment by aborche** [comment]
Fixed build for QEMU 5.0.1

**Comment by ionutnechita** [comment]
Thanks. I will test and return with an update.
