### ISSUE TITLE
Пожалуйста, оформите это как порт и создайте PR в Bugzilla

### ISSUE THREAD

**Issue by click0** [aborche/qemu-guest-agent#15]
Наличие подробной документации это очень хорошо.

Но смысл портов в том, чтобы можно было полностью автоматизировано
установить софт, в том числе затем из пакета одной командой pkg install,
а не следуя разветвленной инструкции.

Желательно в FreeBSD Bugzilla сделать PR и прикрепить туда порт,
оформленный в соответствии с Porters Handbook. Если порт протестирован/поддерживает
только FreeBSD 12+, в Handbook указано, как это оформить в Makefile порта.

**Comment by aborche** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254105
