### ISSUE TITLE
Memory Usage Support

### ISSUE THREAD

**Issue by damienbutt** [aborche/qemu-guest-agent#16]
Should this support memory usage?

I have been through the build process and I have successfully got the agent up and running on a TrueNAS system that is running inside Proxmox.

For the most part, it is working which is great. I can now shutdown or reboot TrueNAS from the Proxmox UI and I also get network information relayed into the Proxmox UI. 

The one thing I noticed straight away was that the amount of memory Proxmox was showing the TrueNAS VM as using was still pretty much 100% which isn't correct. Should it correctly report the memory usage through the agent? Is there any further config I need to do to make this work?

Thanks,

Damien

**Comment by magauthority** [comment]
I've tried and I cannot get this to compile on TrueNas, keep getting the following error: 
root@NetData:~/qemu-guest-agent # make
/!\ ERROR: /!\

Ports Collection support for your FreeBSD version has ended, and no ports are
guaranteed to build on this system. Please upgrade to a supported release.

No support will be provided if you silence this message by defining
ALLOW_UNSUPPORTED_SYSTEM.

Can you point me in the right direction to fix this? 

Thank you.

**Comment by aborche** [comment]
> Should this support memory usage?
> 
> I have been through the build process and I have successfully got the agent up and running on a TrueNAS system that is running inside Proxmox.
> 
> For the most part, it is working which is great. I can now shutdown or reboot TrueNAS from the Proxmox UI and I also get network information relayed into the Proxmox UI.
> 
> The one thing I noticed straight away was that the amount of memory Proxmox was showing the TrueNAS VM as using was still pretty much 100% which isn't correct. Should it correctly report the memory usage through the agent? Is there any further config I need to do to make this work?
> 
> Thanks,
> 
> Damien

guest-get-memory-blocks works only with sysfs on Linux systems.
https://lists.gnu.org/archive/html/qemu-devel/2015-02/msg03521.html
https://bugzilla.redhat.com/show_bug.cgi?id=1751431

**Comment by aborche** [comment]
> I've tried and I cannot get this to compile on TrueNas, keep getting the following error:
> root@NetData:~/qemu-guest-agent # make
> /!\ ERROR: /!\
> 
> Ports Collection support for your FreeBSD version has ended, and no ports are
> guaranteed to build on this system. Please upgrade to a supported release.
> 
> No support will be provided if you silence this message by defining
> ALLOW_UNSUPPORTED_SYSTEM.
> 
> Can you point me in the right direction to fix this?
> 
> Thank you.

update your TrueNAS instance to newest version or use 
make -DALLOW_UNSUPPORTED_SYSTEM

**Comment by damienbutt** [comment]
> I've tried and I cannot get this to compile on TrueNas, keep getting the following error:
> root@NetData:~/qemu-guest-agent # make
> /!\ ERROR: /!\
> 
> Ports Collection support for your FreeBSD version has ended, and no ports are
> guaranteed to build on this system. Please upgrade to a supported release.
> 
> No support will be provided if you silence this message by defining
> ALLOW_UNSUPPORTED_SYSTEM.
> 
> Can you point me in the right direction to fix this?
> 
> Thank you.

Please see the pre-built resource I have posted on the TrueNAS Community forum.

[https://www.truenas.com/community/resources/qemu-guest-agent.167/](url)

I ran through the build in a FreeBSD jail within TrueNAS.
