### ISSUE TITLE
A lot of /bin/df -Ht zombie Process

### ISSUE THREAD

**Issue by harajukakei** [aborche/qemu-guest-agent#17]
I'm using KVM on oVirt 4.4.5. If we install the agent, it will work correctly, but it always create a lot of /bin/df -Ht zombie process which actually make our VM hang (because a lot of process spawned). Using FreeBSD 12.2 and 13 with i440fx.

**Comment by aborche** [comment]
can you show your '/bin/df -Ht' output ?

**Comment by Onepamopa** [comment]
On freebsd 13.0:
/bin/df -Ht
df: option requires an argument -- t
usage: df [-b | -g | -H | -h | -k | -m | -P] [-acilnT] [-t type] [-,]
          [file | filesystem ...]

**Comment by harajukakei** [comment]
> On freebsd 13.0:
> /bin/df -Ht
> df: option requires an argument -- t
> usage: df [-b | -g | -H | -h | -k | -m | -P] [-acilnT] [-t type] [-,]
> [file | filesystem ...]

same output in 12.2 too

**Comment by aborche** [comment]
fixed in https://github.com/aborche/qemu-guest-agent/commit/71edc56b1476bf6c45d1d461bbfa9fe987a8974e
Please try it

**Comment by Onepamopa** [comment]
Are you sure this is the correct commit fix? Because I don't see anything related to "df" in there :) 
The only changed file is README.md :)

**Comment by Onepamopa** [comment]
Nevermind, the commit link went to a totally different commit.

**Comment by aborche** [comment]
> 
> 
> Are you sure this is the correct commit fix? Because I don't see anything related to "df" in there :)
> The only changed file is README.md :)

first comment which you receive in mail is incorrect. i'm change it after sending reply.

**Comment by harajukakei** [comment]
seem it is solved with that commit. will report again tomorrow, i'll let my test vm up for 24 hour.

**Comment by harajukakei** [comment]
confirmed no zombie process created after 24 hrs. hope this fix will integrated asap into official ports tree. thanks.

**Comment by Onepamopa** [comment]
When can we expect the new version @ ports ?

**Comment by aborche** [comment]
> When can we expect the new version @ ports ?

After check issue on ovirt with undefined system info.

**Comment by Onepamopa** [comment]
Also, Qemu 6 ?

**Comment by harajukakei** [comment]
> > When can we expect the new version @ ports ?
> 
> After check issue on ovirt with undefined system info.

any update when we can see this fix in ports tree ? anyway. thankyou for all your efforts. :D
