### ISSUE TITLE
Perl Version

### ISSUE THREAD

**Issue by markwillia** [aborche/qemu-guest-agent#4]
Make errors with:
@bsdbuild:~/qemu-guest-agent # make
===>  qemu-guest-agent-2.9.0_1 Invalid perl5 version 5.28.
*** Error code 1

Stop.
make: stopped in /root/qemu-guest-agent

**Comment by fsrv-xyz** [comment]
Same issue with perl5 version 5.30

**Comment by aborche** [comment]
Fixed
