### ISSUE TITLE
patch-commands-posix issue 

### ISSUE THREAD

**Issue by NikolayDachev** [aborche/qemu-guest-agent#5]
Look like there is a issue with patch-commands-posix

`
===>  License GPLv2 accepted by the user
===>   qemu-guest-agent-3.1.1.1 depends on file: /usr/local/sbin/pkg - found
===> Fetching all distfiles required by qemu-guest-agent-3.1.1.1 for building
===>  Extracting for qemu-guest-agent-3.1.1.1
=> SHA256 Checksum OK for qemu/3.1.1.1/qemu-3.1.1.1.tar.xz.
===>  Patching for qemu-guest-agent-3.1.1.1
===>  Applying extra patch /usr/local/git/github/qemu-guest-agent/files/patch-configure
===>  Applying extra patch /usr/local/git/github/qemu-guest-agent/files/patch-channel-posix
===>  Applying extra patch /usr/local/git/github/qemu-guest-agent/files/patch-commands-posix
2 out of 8 hunks failed--saving rejects to qga/commands-posix.c.rej
*** Error code 1

Stop.
make[1]: stopped in /usr/local/git/github/qemu-guest-agent
*** Error code 1

Stop.
make: stopped in /usr/local/git/github/qemu-guest-agent
`

Any ideas ?

12.0-RELEASE-p11 - fresh install

**Comment by aborche** [comment]
patch for qemu 2.12.2, not for 3.1

**Comment by aborche** [comment]
> Look like there is a issue with patch-commands-posix
> 
> `
> ===> License GPLv2 accepted by the user
> ===> qemu-guest-agent-3.1.1.1 depends on file: /usr/local/sbin/pkg - found
> ===> Fetching all distfiles required by qemu-guest-agent-3.1.1.1 for building
> ===> Extracting for qemu-guest-agent-3.1.1.1
> => SHA256 Checksum OK for qemu/3.1.1.1/qemu-3.1.1.1.tar.xz.
> ===> Patching for qemu-guest-agent-3.1.1.1
> ===> Applying extra patch /usr/local/git/github/qemu-guest-agent/files/patch-configure
> ===> Applying extra patch /usr/local/git/github/qemu-guest-agent/files/patch-channel-posix
> ===> Applying extra patch /usr/local/git/github/qemu-guest-agent/files/patch-commands-posix
> 2 out of 8 hunks failed--saving rejects to qga/commands-posix.c.rej
> *** Error code 1
> 
> Stop.
> make[1]: stopped in /usr/local/git/github/qemu-guest-agent
> *** Error code 1
> 
> Stop.
> make: stopped in /usr/local/git/github/qemu-guest-agent
> `
> 
> Any ideas ?
> 
> 12.0-RELEASE-p11 - fresh install

Fixed
