### ISSUE TITLE
Fix build FreeBSD 12.0-release-p12

### ISSUE THREAD

**Issue by Onepamopa** [aborche/qemu-guest-agent#6]
configure patch was failing (1 out of 2), corrected version @ pull request

**Comment by aborche** [comment]
I will try it on holidays

**Comment by Onepamopa** [comment]
I've tried a few things, but couldn't make it, Feel free to check my fork's "FreeBSD 12.1" branch. It compiles, but breaks at the "make install" part.

**Comment by Onepamopa** [comment]
@aborche  https://github.com/Onepamopa/qemu-guest-agent/tree/FreeBSD-12.1-RELEASE

**Comment by Onepamopa** [comment]
It starts using qemu 4.1.1 on both 12.0-release and 12.1-release, so it should be more or less identical fix for both.

**Comment by Onepamopa** [comment]
Here is a fixed build for freebsd 12.0-release < p10 (including) https://github.com/Onepamopa/qemu-guest-agent/tree/FreeBSD-12.0-RELEASE-p10_OR_LESS

> p10 doesn't work.

**Comment by aborche** [comment]
check out a new fix.
Builds and works ok on FreeBSD 12.0-RELEASE-p10

**Comment by Onepamopa** [comment]
-p10 works, I also compiled the exact same on 12.1-release - worked as well, with qemu3111, read the changed README.md ...

**Comment by Onepamopa** [comment]
So, what about qemu 4.1.1 ?

**Comment by Onepamopa** [comment]
I'm compiling on 12.1 with qemu 4.1.1 and will tell you what happens.

**Comment by Onepamopa** [comment]
Okay, it compiled on 12.1-release with qemu-4.1.1 (I had to remove #include "mntent.h" from commands-posix.c).
The compilation took a long time, probably some X11 features weren't disabled, or new features were added that don't exist in your Makefile --disable-XYZ. I'll test on a new VM later today.

**Comment by Onepamopa** [comment]
Confirmed, a lot of X-related stuff (such as cairo, glib-2.56) gets installed on a clean VM when running building qemu-ga.
Other than that - the agent installs and works normally.

**Comment by Onepamopa** [comment]
I've added some fixes to https://github.com/Onepamopa/qemu-guest-agent/tree/FreeBSD-12.1
The rest (X-related.. I can't yet figure out how to remove)

**Comment by aborche** [comment]
Parent port emulators/qemu should be modified to disable anything x11 related dependencies for agent. Qemu-guest-agent needs only glib2, nothing more

**Comment by Onepamopa** [comment]
Well, I patched the Makefile in the parent port with what's in your readme, it still built all X-related stuff.

**Comment by aborche** [comment]
please try new version. only agent without x11 garbage.

**Comment by Onepamopa** [comment]
I'll check now and let you know.

**Comment by Onepamopa** [comment]
qga/commands-posix.c:29:10: fatal error: 'mntent.h' file not found
#include "mntent.h"
         ^~~~~~~~~~
  CC      qga/qapi-generated/qga-qapi-visit.o
1 error generated.

After removing #include "mntent.h" - compiles and works fine.

**Comment by aborche** [comment]
fixed
