### ISSUE TITLE
port on FreeBSD?

### ISSUE THREAD

**Issue by f-andrey** [aborche/qemu-guest-agent#8]
Hello,

what reason port not commit in FreeBSD?

**Comment by aborche** [comment]
I don't know.
Ask about this port masters. My question holds on bugs.freebsd.org from 2018 year.
Maybe because this port is not fully functional.

**Comment by f-andrey** [comment]
I'm find only https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=232949 not see shar file for add port, surely need new bug

Now qemu probably have commiter and update ;)
I'm add you suffix in second if disable xorg dependency https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=242370

**Comment by aborche** [comment]
Hello, 
last version fully detached from master port settings.
Removed x11, docs, unused components.
Please try a new version.

**Comment by fraenki** [comment]
@aborche Could you please submit your port on bugs.freebsd.org again? Or provide a link to your existing report on bugs.freebsd.org? If your port would be accepted in FreeBSD's ports tree then it would be easier to integrate it into other projects.

**Comment by aborche** [comment]
> @aborche Could you please submit your port on bugs.freebsd.org again? Or provide a link to your existing report on bugs.freebsd.org? If your port would be accepted in FreeBSD's ports tree then it would be easier to integrate it into other projects.

My port is not accepted by port tree maintainers. Why? I don't know.
I'm not create more entries in bugs.freebsd.org with port integration request.

**Comment by fraenki** [comment]
> My port is not accepted by port tree maintainers.

Could you please provide the link to your submission? That would be useful. Thanks!

**Comment by ccesario** [comment]
Hello, 
We have any news about this port to opnsense ?

Thanks

**Comment by aborche** [comment]
Sorry. I haven't a time for it now. Maybe in next month.

**Comment by aborche** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254105
